- README.md
- lib/assets/javascripts/turbograft/turbolinks.coffee
- test/browser/full_page_refresh_test.rb
- test/example/app/views/pages/show.html.erb
Fixes https://github.com/Shopify/turbograft/issues/31
With the `tg-static` attribute decorating a node, we can make sure that this node is not replaced during a fullpage refresh.
Though, if you were to refresh the page at a higher level -- e.g., refreshing an ancestor of the tg-static, the static aspect is no longer obeyed and it is replaced.
I also fixed up `refresh-always` key to literally always refresh the node annotated.  Currently, it was refreshing only if you did a `Page.refresh(onlyKeys: [...])` with some keys, which is pretty bad naming for something called `refresh-always` lol
Potential TODO:
- in another PR, migrate `refresh-always` to `tg-always` or something like that?
cc @tmlayton @alexaitken: the feature we need for a static navigation
cc @tylermercier @celsodantas …
> Add tg-static, fix up refresh-always

- .travis.yml
- lib/assets/javascripts/turbograft/remote.coffee
- lib/turbograft/xhr_headers.rb
- test/controller/pages_controller_test.rb
- test/example/app/views/pages/show.html.erb
@Thibaut @qq99 
I found an issue in our usage of this where redirecting on location.replace would set `session[:_turbolinks_redirect_to]` without headers. This would cause subsequent requests to get redirected when they shouldn't
https://github.com/Shopify/shopify/issues/35973#issuecomment-69338390
Update to latest version of `xhr_headers`: https://github.com/rails/turbolinks/blob/b7553314d82f9907ea6da57361bb4fe9e956eaf6/lib/turbolinks/xhr_headers.rb#L28. I followed the history of xhr_headers, and all changes seem reasonable. 
I have yet to double check this fixes my actual problem :).
> don't set session if redirected not set

- lib/assets/javascripts/turbograft/turbolinks.coffee
- test/javascripts/turbolinks_test.coffee
- test/test_helper.rb
cc @karlhungus 
Bug:
Listening to the TurboGraft emitted event `page:load`, as of `0.1.5`, does not have a list of new nodes in `event.data` as it should have
Explanation:
- `refreshNodes: ->` returns a list of nodes that were refreshed
- When I refactored `refreshNodesWithKeys: ->` into 2 separate fns, `refreshRefreshAlwaysNodes: ->` and `refreshNodesWithKeys: ->` (it previously did both of these in 1 function), I forgot to return `refreshedNodes` properly
- `changePage` returns a list of refreshed nodes or void, and this event is fired:  `triggerEvent 'page:load', nodes`
- ^ previously, `nodes` in the event triggered above was always `null`, now it is something!
Effect:
If you had a listener for `page:load` in your app and were expecting to see a list of nodes you would never see any …
> Fixed a bug with `page:load` event not having proper event.data

- lib/assets/javascripts/turbograft/remote.coffee
- test/javascripts/remote_test.coffee
This will let us properly https://github.com/Shopify/shopify/issues/36350
We can't set `tg-remote` on the products form because the form's `method="POST"` attribute that rails is setting overwrites the `method="PATCH"` hidden field within the form. We should just not set the submission type based on form attributes, and instead use a `_method` hidden field. Ideally we'd look at what's already in `formData` but we can't because FormData is stored in native code and we don't have access.
@qq99 @celsodantas
> Don't automatically add _method to FormData

- lib/assets/javascripts/turbograft/turbolinks.coffee
- test/browser/full_page_refresh_test.rb
- test/example/app/views/pages/show.html.erb
- test/test_helper.rb
When replacing nodes, it seems like `existingNode.parentNode.replaceChild(newNode, existingNode);` will move `newNode` out of any current tree its in, and into the tree where `existingNode` used to sit.
`0.1.5` made `refresh-always` call way more often, not just if there were `onlyKeys` to refresh.  Thus, this line of code was being run & and any `existingNode` that had `refresh-always` on it was being moved from the server-fresh `body` and being placed into `document.body`.  But!-- since it's a full page refresh, the next step is replacing `document.body` with server-fresh `body`, which now lacks this node, leading to the appearance of the `refresh-always` nodes disappearing.
The solution I suggest is to make a deep clone of the node when replacing.
cc @karlhungus @patrickdonovan …
> Prevent refresh-always from destroying nodes

- lib/assets/javascripts/turbograft/turbolinks.coffee
- test/javascripts/turbolinks_test.coffee
cc @patrickdonovan @DrewMartin @tylermercier @celsodantas @kurtfunai 
```coffee
document.addEventListener 'page:load', (event) ->
reset(event.data)
```
This should fix the bug we saw earlier where the returned `nodes` (`event.data` in above listener) during partial-refresh had a stale node inside it.  Ie, nodes that are not even attached to the `window.body`.
An example problematic set of returned nodes from a partial-replace in `0.1.9` is:
- `foo` (a `refresh-always` node)
- `bar` (a `refresh="something"` node that is ancestor of `foo`)
`foo` is first element in array b/c of `refresh-always` processing.  Then `bar` is next because of `onlyKeys` processing.
However, since `bar` encapsulates `foo`, `foo` is stale and no longer in the DOM, but it is returned to any listeners of the event. …
> Avoid returning stale nodes by doing replace in one shot, as it was performed previously

- lib/assets/javascripts/turbograft/turbolinks.coffee
When we refresh the page using turbograft, `autofocus` does not work, only works if you refresh the page.
This was fixed in Turbolinks a while ago, but the fix happened after we branched from it.
I'm just copying the same solution from Turbolinks: https://github.com/rails/turbolinks/commit/3aab7249bb0b695b49f2a31493653f0dce87729c
The comment on Turbolinks that the problem is only happening on Firefox is wrong. It also happens on other browsers as well.
I'm focusing only on `fullpage` refresh. The reason is because I don't see any use case to also do that on partial page refresh.
reviews @kurtfunai @qq99 @karlhungus  @patrickdonovan
> fixing autofocus for fullpage refresh

- lib/assets/javascripts/turbograft/turbolinks.coffee
Closes #62
Originally done because that's what turbolinks does (rails/turbolinks#82) but it looks like either our version of turbolinks or ios chrome doesn't suffer from this bug any more. This will fix https://github.com/Shopify/shopify/issues/29477
@qq99 @patrickdonovan @celsodantas @maartenvg
> Enable turbograft on ios chrome

- lib/assets/javascripts/turbograft/remote.coffee
- test/javascripts/remote_test.coffee
fixes https://github.com/Shopify/shopify/issues/37614
In IE11 it appears that serializing file inputs without data causes issues. This PR adds tg-remote-noserialize which can be used to omit such inputs.
review @qq99 @DrewMartin @maartenvg
> filter out inputs which do not have name attribute

- README.md
- lib/assets/javascripts/turbograft/initializers.coffee
- lib/assets/javascripts/turbograft/remote.coffee
- test/browser/partial_page_refresh_test.rb
- test/example/app/views/pages/show.html.erb
- test/javascripts/initializers_test.coffee
- test/javascripts/remote_test.coffee
Adding `full-refresh-on-success-except` which will allow for selectively omitting parts of the page when refreshing on success.
review @qq99 @karlhungus
> add refresh on success except logic

- lib/assets/javascripts/turbograft/initializers.coffee
While walking the DOM it is possible that parentNode can become null. As a result, the not null check at line 53 may not guard against all null cases. This can be fixed by moving the check into the while loop conditions.
@tylermercier @celsodantas @nsimmons @patrickdonovan @kurtfunai @qq99
> guard parentNode being null when walking DOM

- lib/assets/javascripts/turbograft/initializers.coffee
There was a lot of duplication in `Turbograft.handlers.remoteMethodHandler` and `Turbograft.handlers.remoteFormHandler`. This PR extracts that in a method that builds the `Turbograft.Remote` object based on the target (and a few other params)
@qq99 @DrewMartin
> DRY up remote handler

- README.md
- lib/assets/javascripts/turbograft/turbolinks.coffee
Because of how we replace nodes anything that has jQuery event handlers attached (explicitly attached, not through Twine) will cause the listening object to leak. For example our Form object does several $.on calls in the constructor and because of this it will never be cleaned up. jQuery event handlers are are only cleaned up when you use jQuery methods to remove the nodes.
When calling [remove](http://api.jquery.com/remove/) and [replaceWith](http://api.jquery.com/replaceWith/) "all bound events and jQuery data associated with the elements are removed"
Review
@Thibaut @qq99 @kristianpd @arthurnn 
We should probably push this upstream to turbolinks. Glancing at their code I believe it will have the same problem
Also I'm not sure how to write tests for memory leaks
> Remove nodes with jQuery if available

- lib/assets/javascripts/turbograft/page.coffee
- test/javascripts/page_test.coffee
This allows the user of TurboGraft to register a function to be called *exactly once* when a specific node has been refreshed (be it a full page refresh, or a partial page refresh).
This is mostly a port of what we have in `modules.coffee` in Shopify.  I have not ported `Page.onRefresh` since that definition is more tied to Twine-y things
```coffee
class MyFoo
constructor: (@node) ->
@bindSomeEventsOn(@node)
Page.onReplace(@node, @unbindSomeEvents.bind(this)) # we want to clean up all the events we bound to prevent leaking
unbindSomeEvents = ->
... # undo whatever we did in the `bindSomeEvents` function
```
cc @DrewMartin for primary review
cc also @patrickdonovan @tylermercier @nsimmons @celsodantas
> port over Page.onReplace for reliably running a callback after the node in question has been removed from the DOM

- lib/assets/javascripts/turbograft/page.coffee
- lib/assets/javascripts/turbograft/turbolinks.coffee
- test/javascripts/page_test.coffee
- test/javascripts/turbolinks_test.coffee
Currently we have 2 ways of doing a Page.refresh (also see #73). One where you have an XHR response you want to use to partially replace things in the page. And another where you give in a URI which you want to visit / (partially) refresh the current page, with or without some queryParams. 
So 
```coffeescript
Page.refresh
response: xhr
onlyKeys: [...]
```
vs
```coffeescript
Page.refresh
url: ... # optional, defaults to current page
queryParams: {...} # optional
onlyKeys: [...] # optional, defaults to full page refresh
```
In the first case we don't do a `Turbolinks.pushState` when the refresh is done, which makes sense because you're not leaving the page. In the bottom case we do update the window state, but only if it is a new URL. 9 out of 10 times that's fine, because either you're …
> Optionally prevent PushState on Page.refresh without XHR

- README.md
- lib/assets/javascripts/turbograft/remote.coffee
- test/javascripts/remote_test.coffee
Modified version of #80
This adds a `tg-remote-noserialize` attribute, but unlike the last one it prevents serialization of a node and its subtree. Consider a field that has many inputs inside of it which you want to serialize together, conditionally. Either they're all sent or none of them are. Rather than putting disabled on them individually we can just put `tg-remote-noserialize` on some ancestor of them.
My biggest concern for this was performance. I tried a few different methods and benchmarked them [here](http://jsperf.com/finding-enabled-inputs-by-attribute/3). Tl;dr this method's the fastest in general. In practical terms I tried making a product with 100 variants and 100+ tags, for about 1300 inputs within the main product#show form. I put `tg-remote-noserialize` on each variant …
> Add attribute that prevents serialization of a subtree

- lib/assets/javascripts/turbograft/remote.coffee
- test/javascripts/remote_test.coffee
There are certain situations where it is necessary to use native FormData encoding where `Turbograft.Remote` would not have automatically selected that type of form encoding (https://github.com/Shopify/shopify/pull/43275). 
Therefore, this PR adds an option to `Turbograft.Remote` which allows for specifying that native encoding being used. When not specified, the behaviour is the same as before, i.e. attempt to use URL encoding except when input fields are present.
review @qq99 @DrewMartin @maartenvg 
cc @Shopify/tnt
> add option to specify using native encoding

- lib/assets/javascripts/turbograft/turbolinks.coffee
- test/javascripts/turbolinks_test.coffee
We'd like to programmatically call `Turbolinks.visit` with specific request headers - this PR allows passing headers into the options argument.
Example:
```javascript
Turbolinks.visit('my/resource', {headers: {'foo': 'bar'}});
```
> Allow passing request headers using Turbolinks.visit API.

- lib/turbograft/cookies.rb
- test/controller/pages_controller_test.rb
The presence of a `Set-Cookie` header prevents CDNs from caching a page, so we want to prevent cookies from being set unnecessarily. Turbolinks/Turbograft will assume a request is a GET request if the cookie is not set, so doesn’t doesn’t change Turbograft’s behaviour. 
This mirrors https://github.com/rails/turbolinks/commit/62cc3db457ad9745ccda047dd43ab84fb3d89707
Review: @pushrax @patrickdonovan, cc @mtaher @Shopify/cloud
> Don’t set request_method cookie for GET requests

- lib/turbograft/redirection.rb
I am trying to ensure all public methods are routable, and this one is public but not routable in Shopify.
@pushrax @DrewMartin
> Make redirect_via_turbolinks_to protected

- .travis.yml
- README.md
- lib/assets/javascripts/turbograft/remote.coffee
- test/javascripts/page_test.coffee
- test/javascripts/remote_test.coffee
**This PR adds:**
- The ability for `full-refresh` to behave the same way on Error (422) as it does on Success (200):
- Without the presence of `refresh-on-error`, `full-refresh` will now perform a full page refresh.
- With the presence of `refresh-on-error`, `full-refresh` will perform a partial page replacement using `onlyKeys: @refreshOnError`
- This is in line with how `full-refresh` behaves with `refresh-on-success`.
- `tg-remote-norefresh` now prevents `Page.refresh` on Error (422).
I've gone ahead and fixed the failing `Page.refresh` test on master. All tests are 🍏 :
however builds were broken:
This was due to `rack` requiring ruby version `>=2.2.0`.
After dropping support for ruby versions `<2.2.0` the builds all pass and everything is 🐸 
For review:
@qq99 @dfmcphee @nwtn
> [Fixes Master CI] Allow full refresh to respond to 422

- lib/assets/javascripts/turbograft.coffee
- lib/assets/javascripts/turbograft/turbolinks.coffee
See #114 for discussion
~~Testing this now~~ Works for me!
Only tg-remote seems to use `hasTGAttribute`, and from what I can see, these still work too
cc @dfmcphee @justinthec @Shopify/tnt
> fix obscure refresh-always bug that presents when using data-tg-refresh-always vs refresh-always

- lib/assets/javascripts/turbograft/remote.coffee
- test/javascripts/remote_test.coffee
I have a feeling this is causing https://bugsnag.com/shopify/shopify-js/errors/5666f3c78f2356495b6fe53f?filters%5Bevent.since%5D%5B%5D=30d.
r @qq99 
cc @arapehl
> Bind this.onError for XHR requests in TurboGraft.Remote

- README.md
- test/teaspoon_env.rb
This PR adds more information about running tests to the readme.
This PR also adds a link to some troubleshooting information about why selenium will probably explode when you try to do this, and how to not have it explode.
> add js test info to readme and add environment var for teaspoon driver

- test/browser/full_page_refresh_test.rb
- test/browser/legacy_full_page_refresh_test.rb
- test/browser/legacy_partial_page_refresh_test.rb
- test/browser/partial_page_refresh_test.rb
- test/test_helper.rb
There were a couple cases of
```ruby
has_text = false
while !has_text
has_text = page.assert_text("something")
sleep 1
assert_equal something, 'something'
```
in our test suite and they were causing tests to flake in CI since the `while` loop can sometimes pass the assertion on the first iteration, or fail numerous times in subsequent assertions before exiting the loop.
We fixed them to use `has_text` instead of `assert_text` in https://github.com/Shopify/turbograft/pull/123 and this prevented flakiness since the test would not fail when `has_text` returned false.
However @GoodForOneFare pointed out that Capybara actually has the [built in behaviour](https://github.com/jnicklas/capybara/blob/master/README.md#asynchronous-javascript-ajax-and-friends) to keep repeating a failing assertion …
> Replaced all assert while loops from selenium tests with proper Capybara assertions

- lib/assets/javascripts/turbograft/turbohead.coffee
- test/javascripts/turbolinks_test.coffee
This PR fixes the `sometimes the app breaks` case where a user navigates several times within a TG application using `0.3.0`.
The breakages were the result of `Turbohead#update` missing the upstream document's css when processing it. This only occurred randomly (somewhere between 1/10 and 1/20 times) and only on safari. It seems to be the result of:
```
extractTrackedAssets = (doc) ->
for node in doc.head.children when node.dataset.turbolinksTrack?
node
```
Where the result of extractTrackedAssets would be different than the new implementation:
```
extractTrackedAssets = (doc) ->
return [].slice.call(doc.querySelectorAll('[data-turbolinks-track]'))
```
However, only sometimes, and only on safari. Debugging through or adding `console.log` to the loop steps would make the function perform …
> Fix safari no styles

- lib/assets/javascripts/turbograft/turbolinks.coffee
**What**
This PR fixes null url exceptions by preventing full page navigation on null and introduces `page:error` for cases where `processResponse` fails.
**Why Tho?**
Currently we have quite a lot of `null is not an object` errors from [this line](https://github.com/Shopify/turbograft/blob/master/lib/assets/javascripts/turbograft/turbolinks.coffee#L153) on production where `remote`'s returning an error are causing `turbolinks.loadPage` to be called with `url: null` through `Page.refresh` (bear with me here). 
Passing `newUrl` [here](https://github.com/Shopify/turbograft/blob/master/lib/assets/javascripts/turbograft/page.coffee#L25) would solve the problem by allowing the page to be refreshed when such an error occurs. 
However, we don't actually want to do that, because the user's page …
> fix null url exceptions 

- lib/assets/javascripts/turbograft/turbolinks.coffee
- test/javascripts/turbolinks_test.coffee
This PR fixes partial replaces inadvertently triggering head asset updates. This was usually not causing issues, but in some cases could break stuff.
I should note that this was partially to blame for the spike in `url.absolute` errors. Submitting a remote form would call: 
```
Page.refresh
response: xhr
onlyKeys: @refreshOnSuccess
```
`Page.refresh` would then trigger
```
options.partialReplace = true
options.onLoadFunction = callback
xhr = options.response
delete options.response
Turbolinks.loadPage null, xhr, options
```
Which would then try to update the head assets, with an error callback that looked like:
```
onHeadUpdateError = ->
Turbolinks.fullPageNavigate(url.absolute)
```
Where `url` is null. 
Preventing head asset updates on partial request should fix the new instances of this …
> Fix partial replace head tracking

- README.md
- lib/assets/javascripts/turbograft/turbohead.coffee
- lib/assets/javascripts/turbograft/turbolinks.coffee
- test/javascripts/fixtures/js/routes.coffee
- test/javascripts/turbolinks_test.coffee
I'm very sad tonight.
The graph was causing flickering on new asset bundles no matter how I refactored it due to stylesheet parsing. Load events on link tags weren't working in test environments or some of the browsers I tried. The only solutions seemed to be extremely verbose and hacky (such as setting a polling function to see if asset definitions were loaded by reaching into style tags, or using other nonsense like that)
As such, I just pulled a big old 🔥  and went with the simplest possible solution that gets us what we need.
On the brightside, I kept things at a nice balance of modular and simple, so it should be relatively easy to enhance our solution if/when we think up better ones. If we can work around test environments and are ok with older browsers (like literally firefox from …
> Revert to the simpler solution, :(

- lib/assets/javascripts/turbograft/turbolinks.coffee
- test/javascripts/turbolinks_test.coffee
This PR makes it so that `pushState` is never called when TG does a full page navigation. This behaviour was causing problems when the server cared about the `referrer` because the destination would essentially be double pushed onto the stack in some situations.
We also introduce tests for this behaviour.
**Reviewers**
@GoodForOneFare 
@qq99
> Fix pushState on page refresh

- test/javascripts/component_url_test.coffee
This PR simply adds a test to `ComponentUrl` so that it's behaviour on a null url is clearer to consumers.
@Shopify/tnt 
@qq99 
@GoodForOneFare
> add test for null url to ComponentUrl tests for clarity of intention

- test/javascripts/turbolinks_test.coffee
This PR simplifies tests as suggested in #141.
We minimize multiple calls to `visit` and instead use `startFromFixture` wherever possible. This lets us trust our fixtures to provide the initial state and minimize assertion logic. It should help us avoid silly problems in the future where our tests become broken due to multiple visit calls confusing our stubs / spys. 
note: In some cases we got away with simply removing the first call to `visit` and not bothering with `startFromFixture`.  This is due to the `setup` function already loading an equivalent to `noScriptsOrLinkInHead` every test anyway.
**Reviewers**
@qq99 
@GoodForOneFare
> Simplify tests using startFromFixture and minimizing visits

- README.md
- lib/assets/javascripts/turbograft/turbohead.coffee
- lib/assets/javascripts/turbograft/turbolinks.coffee
- test/example/config/initializers/assets.rb
- test/javascripts/fake_document.coffee
- test/javascripts/fake_script.coffee
- test/javascripts/remote_test.coffee
- test/javascripts/test_helper.js
- test/javascripts/turbohead_test.coffee
- test/javascripts/turbolinks_test.coffee
- test/javascripts/vendor/promise-polyfill/promise.js
Works around a couple of bugs caused by users navigating around quickly (see #151 for reproduction scenarios).  Basically, this change ensures that JS assets are _definitely_ loaded before trying to execute inline scripts.
/cc @TheMallen, @qq99
> Fix concurrent requests

- lib/assets/javascripts/turbograft/turbolinks.coffee
This PR makes `Turbolinks.fullPageNavigate` deal with being given a null xhr by simply doing nothing.
~~I don't really want to merge this yet. It's a last resort to dealing with the `cannot read property 'absolute' of null` errors we've been seeing in production. I'd prefer that we figure out why we're sometimes getting null urls...~~
We're getting null urls when `remote` calls `Page.refresh` with`response: xhr`  and no url. This causes `Page` to call `Turbolinks.loadPage` directly with a `null` url.
Now there are two forks where we end up in 😢 🏠 . If the response doesn't pass `processResponse` then we try to redirect. If it passes `processResponse` but has asset conflicts when `Turbohead` takes a look, we also try to redirect. In both of these cases we attempt to invoke `.absolute` on a …
> defend against nulls in full page navigate

- lib/turbograft.rb
- turbograft.gemspec
This PR bumps the Ruby dependency of TG to Ruby 2.0. This is required for `prepend`.
It also addresses [@phoet's comment](https://github.com/Shopify/turbograft/pull/121#discussion_r74129271).
> Add minimum Ruby version

- lib/assets/javascripts/turbograft/document.coffee
- lib/assets/javascripts/turbograft/response.coffee
- lib/assets/javascripts/turbograft/turbohead.coffee
- lib/assets/javascripts/turbograft/turbolinks.coffee
- test/example/app/assets/config/manifest.js
- test/example/config/initializers/assets.rb
- test/javascripts/document_test.coffee
- test/javascripts/fixtures/js/routes.coffee
- test/javascripts/response_test.coffee
- test/javascripts/turbohead_test.coffee
- test/javascripts/turbolinks_test.coffee
This PR accomplishes two primary goals:
- Address the occasional spikes of `Cannot read property 'match' of null` we've been getting for ages, and hopefully adds enough information to those cases that we can figure out why they're happening.
- Iteratively add some testing / refactor some code out of the main Turbolinks file.
@qq99 
@GoodForOneFare
> Refactor Process Doc, Add new Error

- lib/assets/javascripts/turbograft/turbohead.coffee
- test/javascripts/turbolinks_test.coffee
This PR fixes #147
We'll be able to drop the workaround.
@Shopify/tnt 
@edward
@GoodForOneFare 
@utkarshsaxenashopify
> Fix case of moving from a layout with tracked assets to one with none

- lib/assets/javascripts/turbograft/page.coffee
- lib/assets/javascripts/turbograft/remote.coffee
- lib/assets/javascripts/turbograft/response.coffee
- lib/assets/javascripts/turbograft/turbolinks.coffee
- test/javascripts/fixtures/js/routes.coffee
- test/javascripts/initializers_test.coffee
- test/javascripts/page_test.coffee
- test/javascripts/remote_test.coffee
- test/javascripts/response_test.coffee
- test/javascripts/turbolinks_test.coffee
This PR fixes the two main issues (#157 and #149) with remotes that result in redirects ~~on an opt-in  basis~~, and also refactors some of `Turbolinks` to make it a bit easier to maintain (and to add these changes). 
As we can see with #157 and #149, remotes that result in redirects can be pretty sketchy in the current release of TG. In most cases, a remote resulting in a redirect is due to submitting a form and then being redirected to the html generating endpoint afterwards. This means that we want scroll position to not be affected, and we don't want to bother waiting on head asset tracking. However, some cases (see home card navigation) actually are page navigations in disguise. In these (exceptional) cases there is no elegant solution with the current build of TG and we are …
> Fix remote redirects being all wonky

- .travis.yml
- test/browser/full_page_refresh_test.rb
- test/browser/legacy_full_page_refresh_test.rb
- test/browser/legacy_pages_request_test.rb
- test/browser/legacy_partial_page_refresh_test.rb
- test/browser/pages_request_test.rb
- test/browser/partial_page_refresh_test.rb
- test/example/app/assets/javascripts/application.js
- test/example/app/assets/javascripts/vendor/promise-polyfill/promise.js
- test/test_helper.rb
- turbograft.gemspec
**Fixes #169 (hopefully?)**
~~We just export an environment variable. TBH I'm not sure how this was ever working if travis never had selenium.~~
This was funny. 
- Travis suddenly lacked selenium drivers for FF
- Tried to switch to phantom
- Worked great for js tests
- Didn't work for ruby tests
- Switched ruby tests back to selenium and worked on getting it working
- Had to install geckodriver in the before_script hook
- Had to request a modern firefox build
- Ran into leaky tests (possibly exposed by newer FF build or something?) where test order randomization would cause fails sometimes due to session persistence and our server side TG shenanigans.
- Added `session_reset` logic to fix them
- Had a hilarious number of fails (and thus test restarts) caused by our silly test that compares …
> Fix broken travis scripts, plug up ensuing test leaks.

- test/javascripts/remote_test.coffee
- test/javascripts/turbolinks_test.coffee
This test makes remote test browser runner friendly by sandboxing TG into an iframe just like in the other tests. :)
@Shopify/tnt 
@GoodForOneFare 
@lemonmade
> refactor remote tests to use iframe

- lib/assets/javascripts/turbograft/response.coffee
- lib/assets/javascripts/turbograft/turbolinks.coffee
- test/javascripts/page_test.coffee
- test/javascripts/response_test.coffee
- test/javascripts/turbolinks_test.coffee
- adds a new check that determines redirect status on the client side using `xhr.responseURL` vs our known`intendedURL`
- memoizes `url` onto the `Response` object 
- simplifies browser state updates using `Response.url`
Basically, in some cases we were causing the server to do extra work. It turns out this becomes more apparent when service workers get involved, because you need to know what URL you're actually going to and you can't know it will be a redirect first and... ok well it's hard to explain why but let me tell you it was breaking something fierce.
Imagine if you will, you go to do a thing, and you get redirected. Lucky you, this also happens to be right when we push a new bundle. ATM the following happens:
- TG makes an xhr to the url you wanted, and stores this url
- The …
> client side redirect detection

- lib/turbograft.rb
Currently, if you customize `TurboGraft::Config.controllers`, the listed controllers will be eager loaded.
This is detrimental in big apps, because it will slow down the boot in development mode for no good reason.
This PR allows alternatively to explicitly `include TurboGraft` in the controllers you want it, and it will only take effect when the controller is referenced.
@qq99 @TheMallen @rafaelfranca for review please.
> Allow to configure Turbogradft in a way that doesn't compromise lazy loading

- .gitignore
- .travis.yml
- lib/turbograft/redirection.rb
- test/controller/legacy_pages_controller_test.rb
- test/controller/pages_controller_test.rb
- test/example/app/controllers/legacy_pages_controller.rb
- test/example/app/controllers/pages_controller.rb
- test/test_helper.rb
This fixes CI, was able to get 🍏 twice now 🙏 
Notable changes:
- Fix Mime deprecation re: rails 5
- Fix `render text:` deprecation re: rails 5
Note that `redirect_via_turbolinks_to` is only used in the example app included in this repo, and in tests of said example app.  Perhaps it should be deleted in the future
> Fix CI re: rails deprecations

- dev.yml
- lib/assets/javascripts/turbograft/response.coffee
- lib/assets/javascripts/turbograft/turbolinks.coffee
- test/javascripts/response_test.coffee
- test/javascripts/turbolinks_test.coffee
This PR aims to make TG shippable again.
We've been unable to deploy the latest version of TG in our apps because we relied on some quirky behaviour. Namely, we have multiple call-sites that pass an XHR into `page.refresh` which already has listeners on it, intending those listeners to be invoked after the replace has occurred. The problem arises because changes to loadPage's implementation meant that some of these (which resulted in redirects) were (correctly) detected to not be true partial replaces (they redirected to other routes) and ideally should have head asset tracking.  Since head asset tracking needs to be asynchronous, the code was rendered broken.
TG does have an api for doing things after a particular refresh, with the `callback` option, but these weird cases are very hard …
> 🛠️ Make it shippable
